# yaml-language-server: $schema=https://platen.io/schemas/config/schema.json
# Update to your own settings for URL/title
baseURL: https://kuruso.flagrant.garden/
title:   Kuruso

module:
  imports:
    - path: github.com/platenio/platen/modules/platen

menu:
  before:
    - name: Blog
      url: /posts
      weight: 10

params:
  description: Kuruso, a hyper-fantastic megalopolis setting for adventure and intrigue.
